# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iXpandDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iXpandDemo
  pod 'iXpandSDKObjc', :git => 'https://github.com/leshkoapps/iXpandSDKObjc.git', :commit => '45d7c8eba31e9f4922c0cec3e2b93f066b716534'

end
