# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iXpandDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iXpandDemo
  pod 'iXpandSDKObjc', :git => 'https://github.com/leshkoapps/iXpandSDKObjc.git', :commit => '637ca74a297476bb791d2dfd2c38268e100a93f1'

end
