# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'iXpandDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iXpandDemo
  pod 'iXpandSDKObjc', :git => 'https://github.com/leshkoapps/iXpandSDKObjc.git', :commit => '8e7ecb8e6b1739bc20b77d025478722b80564d5b'

end
